name: Unit Test Generation Workflow
on:
  push

jobs:
  test-generation:
    
    if: contains(github.event.head_commit.message, 'OPIX-GEN-UNIT-TEST')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: recursive


      - name: Install dependencies
        run: npm install
     
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run forge install 
        run: |
          forge install


      - name: Unit Test Generator
        uses: olympix/test-generator@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
          OLYMPIX_GITHUB_ACCESS_TOKEN: ${{ secrets.OLYMPIX_GITHUB_TOKEN }}
